### ISSUE TITLE
Multiple Moderators with IndProd

### ISSUE THREAD

**Issue by fawad83** [yrosseel/lavaan#188] opened 2020-07-23 11:22 UTC
Hi

I wrote the code with single continuous moderator using indProd. What if i have two continuous moderators. Will i use two indProd functions

Here is my code and it works fine

library(haven)
library(lavaan)
library(semTools)
library(stargazer) # makes nice tables
Data <- read_sav("C:/Users/kfls_/Google Drive/Freelancing/Ghada/New Analysis 13-7-20/R Analysis/DataDel.sav")
Data <- Data[,c(6:21,24:26,28:36)]
names(Data) <- c('ID1', 'ID2', 'ID3', 'ID4', 'ID5', 'ID6', 'ID7', 'ID8', 'ID10', 'ID11', 'ID12', 'ID13', 'ID14', 'ID15', 'ID16', 'ID17','CORR1','CORR2','CORR3', 'EO1', 'EO2', 'EO3', 'EO4', 'EO5', 'EO6', 'EO7', 'EO8', 'EO9')

Data.dmc <- indProd(Data, var1 = c('ID1', 'ID2', 'ID3', 'ID4', 'ID5', 'ID6', 'ID7', 'ID8', 'ID10', 'ID11', 'ID12', 'ID13', 'ID14', 'ID15', 'ID16', 'ID17'), var2 = c('CORR1','CORR2','CORR3'), match=FALSE, meanC=TRUE, residualC=FALSE, doubleMC=TRUE)

IDs.dmc.syntax <- 
'
ID_R =~ ID1 + ID2 + ID3 + ID4 + ID5
ID_C =~ ID6 + ID7 + ID8 + ID10
ID_K =~ ID11 + ID12 + ID13
ID_N =~ ID14 + ID15 + ID16 + ID17
ID_SEC =~ ID_R + ID_C + ID_K + ID_N
CORR_C =~ xx*CORR1 + xx*CORR2 + xx*CORR3

MODing =~ ID1*CORR1 + ID2*CORR1 + ID3*CORR1 + ID4*CORR1 + ID5*CORR1 + ID6*CORR1 
+ ID7*CORR1 + ID8*CORR1 + ID10*CORR1 +ID11*CORR1 + ID12*CORR1 + ID13*CORR1 
+ ID14*CORR1 + ID15*CORR1 + ID16*CORR1 + ID17*CORR1 +ID1*CORR2 + ID2*CORR2 
+ ID3*CORR2 + ID4*CORR2 + ID5*CORR2 + ID6*CORR2 + ID7*CORR2 + ID8*CORR2 
+ ID10*CORR2 + ID11*CORR2 + ID12*CORR2 + ID13*CORR2 + ID14*CORR2 + ID15*CORR2 
+ ID16*CORR2 + ID17*CORR2 + ID1*CORR3 + ID2*CORR3 + ID3*CORR3 + ID4*CORR3 
+ ID5*CORR3 + ID6*CORR3 + ID7*CORR3 + ID8*CORR3 + ID10*CORR3 +ID11*CORR3 
+ ID12*CORR3 + ID13*CORR3 + ID14*CORR3 + ID15*CORR3 + ID16*CORR3 + ID17*CORR3

EO_C =~ EO1 + EO2 +EO3 +EO4 +EO5 +EO6 +EO7 +EO8 +EO9

EO2 ~~ EO5
EO3 ~~ EO4
EO8 ~~ EO9
EO2 ~~ EO3
ID16 ~~ ID17
EO_C ~ ID_SEC + CORR_C + MODing
'

IDs.dmc.fit <-sem(IDs.dmc.syntax, data=Data.dmc, std.lv=TRUE, estimator="mlr")
fitMeasures(IDs.dmc.fit)
summary(IDs.dmc.fit, standardized=TRUE)

**Comment by TDJorgensen** [comment] 2020-07-24 14:27
In the interest of being able to utilize your syntax example, could you embed the syntax within triple-backticks?  That way, the operators within the R syntax will be printed rather than interpreted as Markdown operators (e.g., asterisks signal italicization). It would also be helpful to provide some (simulated or real) data, to make your example reproducible. 

> Will i use two indProd functions

No, one `indProd()` call is sufficient.  See the example on the `?probe3WayMC` help page.

**Comment by TDJorgensen** [comment] 2020-07-24 14:29
And since this is not a lavaan issue but a semTools issue, I will close this issue.  If you do continue to experience trouble with a semTools function, please open an issue on the simsem/semTools GitHub page, or you can post a question on lavaan's Google group.

**Closed** 2020-07-26 17:54 UTC
