### ISSUE TITLE
No way to parallelize bootstrap when calling sem/cfa/lavaan

### ISSUE THREAD

**Issue by mdekstrand** [yrosseel/lavaan#23] opened 2014-05-07 15:58 UTC
As near as I can tell, while the bootstrapping code supports parallelism, there is no way to pass the `parallel` option through a call to `sem` or `lavaan`.

**Comment by cvanpay** [comment] 2019-09-05 23:38
Is parallel within bootstrapLavaan( ) supposed to speed up bootstrapping, or to specify some optimization/start across multiple cores as described above? I can't get either "snow" or "parallel" in the parallel arg to do anything on more than a single core (total), both when i use ncpus = detectCores( )) or ncpus = 16. This is also evidenced by the same exact system.time with and without the parallel call. (Sorry to necro this thread!)

**Comment by TDJorgensen** [comment] 2019-09-06 12:44
It helps to provide a reproducible script.  I just tried the help-page example with `R=100` on my MacBook, which has `detectCores()` = 12 virtual cores, and indeed the run times are essentially the same.

```
HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '

fit <- cfa(HS.model, data=HolzingerSwineford1939, se="none")

system.time(T.boot <- bootstrapLavaan(fit, R=100, type="bollen.stine",
                                      FUN=fitMeasures, fit.measures="chisq"))
#   user  system elapsed 
#  2.161   0.041   2.202 

system.time(T.boot <- bootstrapLavaan(fit, R=100, type="bollen.stine",
                                      FUN=fitMeasures, fit.measures="chisq",
                                      parallel = "multicore",
                                      ncpus = parallel::detectCores() - 1L))
#   user  system elapsed 
#  1.972   0.032   2.004 
```

Yves, if you haven't already noticed this, I found the problem on [line 104](https://github.com/yrosseel/lavaan/blob/master/R/lav_bootstrap.R#L104) where the parallel options in `lavoptions.` are ignored when the lavaan object is passed to `bootstrap.internal()`.  I suppose below that, the parallel options in `lavoptions.` could be appended to the `lavoptions` list from the `@Options` slot.  Or on lines 129-132 those options could be extracted from `lavoptions.` regardless of whether `is.null(object)`.

**Comment by TDJorgensen** [comment] 2019-09-06 12:45
And thanks for noticing this, Craig!

**Comment by sfcheung** [comment] 2021-10-02 03:11
I am exploring the bootstrapping options of `lavaan()` (not `boostrapLavaan()`) and found that `parallel` does work for `lavaan` if bootstrapping SEs are requested, but `ncpus` must be set, and `cl` is not supported.

```
# Example from https://lavaan.ugent.be/tutorial/mediation.html
# OS: Windows 10
# R: 4.1.1
# lavaan: 0.6-9

options(width = 132)
library(lavaan)
set.seed(1234)
X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)
Data <- data.frame(X = X, Y = Y, M = M)
model <- ' # direct effect
             Y ~ c*X
           # mediator
             M ~ a*X
             Y ~ b*M
           # indirect effect (a*b)
             ab := a*b
           # total effect
             total := c + (a*b)
         '

system.time(fit <- sem(model, data = Data, se = "boot", bootstrap = 2000, parallel ="snow", ncpus = 8))
system.time(fit <- sem(model, data = Data, se = "boot", bootstrap = 2000))
```

The results:

```
> system.time(fit0 <- sem(model, data = Data, se = "boot", bootstrap = 2000, parallel ="snow", ncpus = 8))
   user  system elapsed 
   0.20    0.06    7.18
> system.time(fit1 <- sem(model, data = Data, se = "boot", bootstrap = 2000))
   user  system elapsed 
  30.08    0.55   31.40
```

I checked the task manager and the first run indeed launched eight processes as expected. I also checked the output and confirmed that bootstrapping was indeed conducted and the bootstrapping estimates were stored.

`lavaan()` calls `lav_model_vcov()` to compute the VCOV, which is needed to for the standard errors. If bootstrapping SEs are requested, `lav_model_vcov()` will call `lav_bootstrap_internal`, which is also used by `bootstrapLavaan()`. Therefore, `lavaan()` and its wrappers can support parallelized bootstrapping, though I am not sure whether this is intended or accidental.

However, to do parallelized bootstrapping, `ncpus` must be set. The argument of `cl` of `bootstrapLavaan()` cannot be used because it conflicts with the other option, `clustered`, I believe. The following code won't work:

```
my_cl <- parallel::makeCluster(8)
system.time(fit0 <- sem(model, data = Data, se = "boot", bootstrap = 2000, parallel ="snow", cl = my_cl))
# Error in lav_options_set(opt) : 
#   lavaan ERROR: `se' argument must one of "none", "robust.cluster", or "robust.cluster.sem" in the clustered case
# Timing stopped at: 0 0 0
```

I have not tried `multicore` because I don't have a linux box.

**Comment by yrosseel** [comment] 2022-06-21 12:00
There was indeed a name clash between the 'clustered=' argument, and the 'cl=' argument. This is a result of the partial matching mechanism that is used by R. This is now prevented in 0.6-12. As a result, all the parallelization arguments are now passed to lav_bootstrap_internal(). In addition, ncpus is now automatically set to the number of cores minus one. This is now also documented in man page of lavOptions().

Both sem()/lavaan() and bootstrapLavaan() now seem to work correctly (in 0.6-12) when parallelization is requested (at least on my linux box).

I will now close this (very old) issue. For further remarks/reports concerning the bootstrap and/or parallelization, please open a new issue.

**Closed by yrosseel** 2022-06-21 12:00 UTC
Labels: bug
